export const PROTOCOL_MAL: Record<string, string[]> = {
    TCP: [
        '-e', 'frame.number',
        '-e', 'frame.time_epoch',
        '-e', 'frame.len',
        '-e', 'ip.src',
        '-e', 'ip.dst',
        '-e', 'ip.proto',
        '-e', '_ws.col.Protocol',
        '-e', 'tcp.srcport',
        '-e', 'tcp.dstport',
        '-e', 'tcp.analysis.retransmission',
    ],
    UDP: [
        '-e', 'frame.number',
        '-e', 'frame.time_epoch',
        '-e', 'frame.len',
        '-e', 'ip.src',
        '-e', 'ip.dst',
        '-e', 'ip.proto',
        '-e', '_ws.col.Protocol',
        '-e', 'udp.srcport',
        '-e', 'udp.dstport',
        '-e', 'udp.length',
    ],
    ICMP: [
        '-e', 'frame.number',
        '-e', 'frame.time_epoch',
        '-e', 'frame.len',
        '-e', 'ip.src',
        '-e', 'ip.dst',
        '-e', 'ip.proto',
        '-e', '_ws.col.Protocol',
        '-e', 'icmp.type',
        '-e', 'icmp.code',
        '-e', 'icmp.ident',
        '-e', 'icmp.seq',
    ],
    QUIC: [
        '-e', 'frame.number',
        '-e', 'frame.time_epoch',
        '-e', 'frame.len',
        '-e', 'ip.src',
        '-e', 'ip.dst',
        '-e', 'ip.proto',
        '-e', '_ws.col.Protocol',
        '-e', 'quic.scid',
        '-e', 'quic.packet_number',
        '-e', 'quic.length',
        '-e', 'quic.version',
    ],
} as const;